// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"github.com/mazrean/kessoku"
	"github.com/mazrean/kessoku/internal/kessoku/testdata/external_set/pkga"
	"github.com/mazrean/kessoku/internal/kessoku/testdata/external_set/pkgb"
)

func InitializeA() *pkga.A {
	b := kessoku.Provide(pkgb.NewB).Fn()()
	a := kessoku.Provide(pkga.NewA).Fn()(b)
	return a
}
func InitializeApp() *App {
	b := kessoku.Provide(pkgb.NewB).Fn()()
	a := kessoku.Provide(pkga.NewA).Fn()(b)
	app := kessoku.Provide(NewApp).Fn()(a)
	return app
}
