// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeService() *Service {
	databaseConfig, cacheConfig := kessoku.Provide(NewConfigs).Fn()()
	service := kessoku.Provide(NewService).Fn()(databaseConfig, cacheConfig)
	return service
}
