// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeService() *Service {
	loggerFunc := kessoku.Provide(NewLoggerFunc).Fn()()
	service := kessoku.Provide(NewService).Fn()(loggerFunc)
	return service
}
