// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeApp() (*App, error) {
	v0 := kessoku.Provide(NewConfig).Fn()()
	v1 := kessoku.Provide(NewServer).Fn()(v0)
	v2, err := kessoku.Provide(NewDatabase).Fn()(v0)
	if err != nil {
		var zero *App
		return zero, err
	}
	v3 := kessoku.Provide(NewUserService).Fn()(v2)
	v4 := kessoku.Provide(NewApp).Fn()(v1, v3)
	return v4, nil
}
func InitializeAppWithSets() (*App, error) {
	v0 := kessoku.Provide(NewConfig).Fn()()
	v1 := kessoku.Provide(NewServer).Fn()(v0)
	v2, err := kessoku.Provide(NewDatabase).Fn()(v0)
	if err != nil {
		var zero *App
		return zero, err
	}
	v3 := kessoku.Provide(NewUserService).Fn()(v2)
	v4 := kessoku.Provide(NewApp).Fn()(v1, v3)
	return v4, nil
}
func InitializeUserService() (*UserService, error) {
	v0 := kessoku.Provide(NewConfig).Fn()()
	v1, err := kessoku.Provide(NewDatabase).Fn()(v0)
	if err != nil {
		var zero *UserService
		return zero, err
	}
	v2 := kessoku.Provide(NewUserService).Fn()(v1)
	return v2, nil
}
func InitializeAppWithNestedSets() (*App, error) {
	v0 := kessoku.Provide(NewConfig).Fn()()
	v1 := kessoku.Provide(NewServer).Fn()(v0)
	v2, err := kessoku.Provide(NewDatabase).Fn()(v0)
	if err != nil {
		var zero *App
		return zero, err
	}
	v3 := kessoku.Provide(NewUserService).Fn()(v2)
	v4 := kessoku.Provide(NewApp).Fn()(v1, v3)
	return v4, nil
}
