// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func GetService() (*Service, error) {
	val := kessoku.Provide(NewDB).Fn()()
	service := kessoku.Provide(NewService).Fn()(val)
	var err error
	err = kessoku.Provide(ValidateDB).Fn()(val)
	if err != nil {
		var zero *Service
		return zero, err
	}
	return service, nil
}
