// Code generated by kessoku. DO NOT EDIT.

//go:build !wireinject

package main

import (
	"context"
	"github.com/mazrean/kessoku"
)

func InitServer(ctx context.Context, config *Config) (*Server, error) {
	var err error
	db, err := kessoku.Provide(NewDB).Fn()(ctx, config)
	if err != nil {
		var zero *Server
		return zero, err
	}
	server := kessoku.Provide(NewServer).Fn()(db, config)
	return server, nil
}
