// Code generated by kessoku. DO NOT EDIT.

//go:build !wireinject

package main

import "github.com/mazrean/kessoku"

func InitializeService() *Service {
	option := kessoku.Provide(NewOption).Fn()()
	service := kessoku.Provide(NewService).Fn()(option)
	return service
}
