// Code generated by kessoku. DO NOT EDIT.

//go:build !wireinject

package main

import "github.com/mazrean/kessoku"

func InitializeService() *Service {
	service := kessoku.Provide(NewService).Fn()()
	return service
}
