// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeService(str string, str0 string) *Service {
	service := kessoku.Provide(NewService).Fn()(str, str0)
	return service
}
