// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitApp(str string) (*App, error) {
	var err error
	err = kessoku.Value((error)(nil)).Fn()()
	if err != nil {
		var zero *App
		return zero, err
	}
	app := kessoku.Provide(NewApp).Fn()(str)
	return app, nil
}
