// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"context"
	"github.com/mazrean/kessoku"
	"github.com/mazrean/kessoku/internal/kessoku/testdata/external_set_async_bind/pkgx"
	"golang.org/x/sync/errgroup"
)

func InitializeApp(ctx context.Context) (*App, error) {
	var (
		greeterImpl pkgx.Greeter
		other       *pkgx.Other
		otherCh     = make(chan struct{})
		app         *App
	)
	parentCtx := ctx
	ctx, cancel := context.WithCancel(ctx)
	eg, ctx := errgroup.WithContext(ctx)
	defer func() {
		cancel()
		_ = eg.Wait()
	}()
	eg.Go(func() error {
		var err error
		other, err = kessoku.Async(kessoku.Provide(pkgx.NewOther)).Fn()()
		if err != nil {
			if cause := context.Cause(ctx); cause != nil {
				return cause
			}
			return err
		}
		close(otherCh)
		return nil
	})
	var err0 error
	greeterImpl, err0 = kessoku.Async(kessoku.Bind[pkgx.Greeter](kessoku.Provide(pkgx.NewGreeter))).Fn()()
	if err0 != nil {
		if cause := context.Cause(ctx); cause != nil {
			var zero *App
			return zero, cause
		}
		var zero *App
		return zero, err0
	}
	select {
	case <-otherCh:
	case <-ctx.Done():
		var zero *App
		return zero, context.Cause(ctx)
	}
	app = kessoku.Provide(NewApp).Fn()(greeterImpl, other)
	if err := eg.Wait(); err != nil {
		var zero *App
		return zero, err
	}
	if err := context.Cause(parentCtx); err != nil {
		var zero *App
		return zero, err
	}
	return app, nil
}
