// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeEventHandler() *EventHandler {
	eventChan := kessoku.Provide(NewEventChannel).Fn()()
	eventHandler := kessoku.Provide(NewEventHandler).Fn()(eventChan)
	return eventHandler
}
