// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"github.com/mazrean/kessoku"
	"github.com/mazrean/kessoku/internal/kessoku/testdata/external_set_duplicate/pkga"
	"github.com/mazrean/kessoku/internal/kessoku/testdata/external_set_duplicate/pkgc"
)

func InitializeA() *pkga.A {
	c := kessoku.Provide(pkgc.NewC).Fn()()
	a := kessoku.Provide(pkga.NewA).Fn()(c)
	return a
}
