// Code generated by kessoku. DO NOT EDIT.

//go:build !wireinject

package main

import (
	"context"
	"github.com/mazrean/kessoku"
	"golang.org/x/sync/errgroup"
)

func InitializeService(val Ctx) (*Service, error) {
	var (
		config  *Config
		cache   *Cache
		cacheCh = make(chan struct{})
		service *Service
	)
	parentCtx := val
	val, cancel := context.WithCancel(val)
	eg, val := errgroup.WithContext(val)
	defer func() {
		cancel()
		_ = eg.Wait()
	}()
	eg.Go(func() error {
		var err error
		cache, err = kessoku.Async(kessoku.Provide(NewCache)).Fn()(val)
		if err != nil {
			return err
		}
		close(cacheCh)
		return nil
	})
	var err0 error
	config, err0 = kessoku.Async(kessoku.Provide(NewConfig)).Fn()(val)
	if err0 != nil {
		var zero *Service
		return zero, err0
	}
	select {
	case <-cacheCh:
	case <-val.Done():
		var zero *Service
		return zero, context.Cause(val)
	}
	service = kessoku.Provide(NewService).Fn()(config, cache)
	if err := eg.Wait(); err != nil {
		var zero *Service
		return zero, err
	}
	if err := context.Cause(parentCtx); err != nil {
		var zero *Service
		return zero, err
	}
	return service, nil
}
