// Code generated by kessoku. DO NOT EDIT.

//go:build !wireinject

package main

import "github.com/mazrean/kessoku"

func InitializeDatabase() *Database {
	config := kessoku.Provide(NewConfig).Fn()()
	database := kessoku.Provide(NewDatabase).Fn()(config)
	return database
}
