// Code generated by kessoku. DO NOT EDIT.

//go:build !wireinject

package main

import "github.com/mazrean/kessoku"

func InitializeService() *Service {
	databaseRepo := kessoku.Async(kessoku.Bind[Repository](kessoku.Provide(NewDatabaseRepo))).Fn()()
	service := kessoku.Provide(NewService).Fn()(databaseRepo)
	return service
}
