// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"context"
	"github.com/mazrean/kessoku"
)

func InitializeService(ctx context.Context) *Service {
	databaseRepo := kessoku.Async(kessoku.Bind[Repository](kessoku.Provide(NewDatabaseRepo))).Fn()()
	service := kessoku.Provide(NewService).Fn()(databaseRepo)
	return service
}
