// Code generated by kessoku. DO NOT EDIT.

//go:build !wireinject

package main

import (
	"context"
	"github.com/mazrean/kessoku"
	"golang.org/x/sync/errgroup"
)

func InitializeApp(ctx context.Context) (*App, error) {
	var (
		config   *Config
		configCh = make(chan struct{})
		db       *DB
		cache    *Cache
		cacheCh  = make(chan struct{})
		app      *App
	)
	parentCtx := ctx
	ctx, cancel := context.WithCancel(ctx)
	eg, ctx := errgroup.WithContext(ctx)
	defer func() {
		cancel()
		_ = eg.Wait()
	}()
	eg.Go(func() error {
		select {
		case <-configCh:
		case <-ctx.Done():
			return context.Cause(ctx)
		}
		var err error
		db, err = kessoku.Async(kessoku.Provide(NewDB)).Fn()(config)
		if err != nil {
			if cause := context.Cause(ctx); cause != nil {
				return cause
			}
			return err
		}
		select {
		case <-cacheCh:
		case <-ctx.Done():
			return context.Cause(ctx)
		}
		app = kessoku.Provide(NewApp).Fn()(db, cache)
		return nil
	})
	config = kessoku.Provide(NewConfig).Fn()()
	close(configCh)
	cache = kessoku.Provide(NewCache).Fn()(config)
	close(cacheCh)
	if err := eg.Wait(); err != nil {
		var zero *App
		return zero, err
	}
	if err := context.Cause(parentCtx); err != nil {
		var zero *App
		return zero, err
	}
	return app, nil
}
