// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeService() *Service {
	val := kessoku.Value(config).Fn()()
	val0 := kessoku.Value(tags).Fn()()
	service := kessoku.Provide(NewService).Fn()(val, val0)
	return service
}
