// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"context"
	"github.com/mazrean/kessoku"
)

func InitializeService(ctx context.Context) (*Service, error) {
	config := kessoku.Provide(NewConfig).Fn()()
	var err error
	database, err := kessoku.Provide(NewDatabase).Fn()(ctx, config)
	if err != nil {
		var zero *Service
		return zero, err
	}
	service := kessoku.Provide(NewService).Fn()(database)
	return service, nil
}
