// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"context"
	"github.com/mazrean/kessoku"
	"golang.org/x/sync/errgroup"
)

func InitializeApp(ctx context.Context) (*App, error) {
	var (
		database *Database
		cache    *Cache
		cacheCh  = make(chan struct{})
		app      *App
	)
	parentCtx := ctx
	ctx, cancel := context.WithCancel(ctx)
	eg, ctx := errgroup.WithContext(ctx)
	defer func() {
		cancel()
		_ = eg.Wait()
	}()
	eg.Go(func() error {
		var err error
		cache, err = kessoku.Async(kessoku.Provide(NewCache)).Fn()(ctx)
		if err != nil {
			if cause := context.Cause(ctx); cause != nil {
				return cause
			}
			return err
		}
		close(cacheCh)
		return nil
	})
	var err0 error
	database, err0 = kessoku.Async(kessoku.Provide(NewDatabase)).Fn()(ctx)
	if err0 != nil {
		if cause := context.Cause(ctx); cause != nil {
			var zero *App
			return zero, cause
		}
		var zero *App
		return zero, err0
	}
	select {
	case <-cacheCh:
	case <-ctx.Done():
		var zero *App
		return zero, context.Cause(ctx)
	}
	app = kessoku.Provide(NewApp).Fn()(database, cache)
	if err := eg.Wait(); err != nil {
		var zero *App
		return zero, err
	}
	if err := context.Cause(parentCtx); err != nil {
		var zero *App
		return zero, err
	}
	return app, nil
}
