// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeUserService() (*UserService, error) {
	config := kessoku.Provide(NewConfig).Fn()()
	var err error
	database, err := kessoku.Provide(NewDatabase).Fn()(config)
	if err != nil {
		var zero *UserService
		return zero, err
	}
	userService := kessoku.Provide(NewUserService).Fn()(database)
	return userService, nil
}
func InitializeCacheService() *CacheService {
	config0 := kessoku.Provide(NewConfig).Fn()()
	cache := kessoku.Provide(NewCache).Fn()(config0)
	cacheService := kessoku.Provide(NewCacheService).Fn()(cache)
	return cacheService
}
func InitializeConfig() *Config {
	config1 := kessoku.Provide(NewConfig).Fn()()
	return config1
}
