// Code generated by kessoku. DO NOT EDIT.

//go:build !wireinject

package main

import "github.com/mazrean/kessoku"

func InitializeHandler() *Handler {
	middlewareList := kessoku.Provide(NewMiddlewares).Fn()()
	handler := kessoku.Provide(NewHandler).Fn()(middlewareList)
	return handler
}
