// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"context"
	"github.com/mazrean/kessoku"
	"golang.org/x/sync/errgroup"
)

func InitializeApp(ctx context.Context) *App {
	var (
		syncService    *SyncService
		asyncService   *AsyncService
		asyncServiceCh = make(chan struct{})
		app            *App
	)
	eg, ctx := errgroup.WithContext(ctx)
	eg.Go(func() error {
		asyncService = kessoku.Async(kessoku.Provide(NewAsyncService)).Fn()()
		close(asyncServiceCh)
		return nil
	})
	syncService = kessoku.Provide(NewSyncService).Fn()()
	<-asyncServiceCh
	app = kessoku.Provide(NewApp).Fn()(syncService, asyncService)
	_ = eg.Wait()
	return app
}
