// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeApp() *App {
	database := kessoku.Provide(NewDatabase).Fn()()
	serviceA := kessoku.Provide(NewServiceA).Fn()(database)
	serviceB := kessoku.Provide(NewServiceB).Fn()(database)
	app := kessoku.Provide(NewApp).Fn()(serviceA, serviceB)
	return app
}
