// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeApp() *App {
	config := kessoku.Provide(NewConfig).Fn()()
	logger := kessoku.Provide(NewLogger).Fn()()
	database := kessoku.Provide(NewDatabase).Fn()(config, logger)
	cache := kessoku.Provide(NewCache).Fn()(database)
	app := kessoku.Provide(NewApp).Fn()(cache)
	return app
}
