// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeService() *Service {
	config := kessoku.Provide(NewConfig).Fn()()
	str := config.APIKey
	num := config.CacheTTL
	flag := config.DebugMode
	service := kessoku.Provide(NewService).Fn()(str, num, flag)
	return service
}
