// Code generated by kessoku. DO NOT EDIT.

//go:build !wireinject

package main

import (
	"context"
	"github.com/mazrean/kessoku"
)

func InitializeService(ctx context.Context) *Service {
	config := kessoku.Provide(NewConfig).Fn()()
	str := config.APIKey
	num := config.CacheTTL
	flag := config.DebugMode
	service := kessoku.Provide(NewService).Fn()(str, num, flag)
	return service
}
