// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeUserService() *UserService {
	v0 := kessoku.As[UserRepository](kessoku.Provide(NewDatabaseUserRepository)).Fn()()
	v1 := kessoku.As[Logger](kessoku.Provide(NewConsoleLogger)).Fn()()
	v2 := kessoku.Provide(NewUserService).Fn()(v0, v1)
	return v2
}
