// Code generated by kessoku. DO NOT EDIT.

//go:build !wireinject

package main

import (
	"github.com/mazrean/kessoku"
	"net/http"
	"sync/atomic"
)

func InitializeHTTPClientPtr() *atomic.Pointer[*http.Client] {
	pointer := kessoku.Provide(NewHTTPClientPtr).Fn()()
	return pointer
}
