// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeComplexService() *Service {
	config := kessoku.Provide(NewConfig).Fn()()
	interfaceValue := kessoku.Bind[Interface](kessoku.Provide(NewConcreteImpl)).Fn()()
	str := kessoku.Value("example value").Fn()()
	num := kessoku.Provide(NewExampleArg).Fn()()
	service := kessoku.Provide(NewService).Fn()(config, interfaceValue, str, num)
	return service
}
