// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeComplexService(arg int) *Service {
	v0 := kessoku.Provide(NewConfig).Fn()()
	v1 := kessoku.Bind[Interface](kessoku.Provide(NewConcreteImpl)).Fn()()
	v2 := kessoku.Value("example value").Fn()()
	v3 := kessoku.Provide(NewService).Fn()(v0, v1, v2, arg)
	return v3
}
