// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/mazrean/kessoku"
)

func InitializeComplexService(num int) *Service {
	config := kessoku.Provide(NewConfig).Fn()()
	concreteImpl := kessoku.Bind[Interface](kessoku.Provide(NewConcreteImpl)).Fn()()
	str := kessoku.Value("example value").Fn()()
	service := kessoku.Provide(NewService).Fn()(config, concreteImpl, str, num)
	return service
}
