// Code generated by kessoku. DO NOT EDIT.

//go:build !wireinject

package main

import "github.com/mazrean/kessoku"

func InitializeService() *Service {
	repository := kessoku.Provide(NewRepository).Fn()()
	service := kessoku.Provide(NewService).Fn()(repository)
	return service
}
