// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"github.com/mazrean/kessoku"
	"golang.org/x/sync/errgroup"
)

func InitializeApp() *App {
	var (
		databaseService       *DatabaseService
		cacheService          *CacheService
		cacheServiceCh        = make(chan struct{})
		messagingService      *MessagingService
		messagingServiceCh    = make(chan struct{})
		userService           *UserService
		notificationService   *NotificationService
		notificationServiceCh = make(chan struct{})
		app                   *App
	)
	eg := &errgroup.Group{}
	messagingService = kessoku.Async(kessoku.Provide(NewMessagingService)).Fn()()
	close(messagingServiceCh)
	eg.Go(func() error {
		databaseService = kessoku.Async(kessoku.Provide(NewDatabaseService)).Fn()()
		<-cacheServiceCh
		userService = kessoku.Provide(NewUserService).Fn()(databaseService, cacheService)
		<-notificationServiceCh
		app = kessoku.Provide(NewApp).Fn()(userService, notificationService)
		return nil
	})
	eg.Go(func() error {
		cacheService = kessoku.Async(kessoku.Provide(NewCacheService)).Fn()()
		close(cacheServiceCh)
		<-messagingServiceCh
		notificationService = kessoku.Provide(NewNotificationService).Fn()(messagingService)
		close(notificationServiceCh)
		return nil
	})
	eg.Wait()
	return app
}
