// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"context"
	"github.com/mazrean/kessoku"
	"golang.org/x/sync/errgroup"
)

func InitializeApp(ctx context.Context) (*App, error) {
	var (
		databaseService    *DatabaseService
		cacheService       *CacheService
		cacheServiceCh     = make(chan struct{})
		messagingService   *MessagingService
		messagingServiceCh = make(chan struct{})
		app                *App
	)
	eg, ctx := errgroup.WithContext(ctx)
	eg.Go(func() error {
		var err error
		databaseService, err = kessoku.Async(kessoku.Provide(NewDatabaseService)).Fn()()
		if err != nil {
			return err
		}
		for _, ch := range []<-chan struct{}{cacheServiceCh, messagingServiceCh} {
			select {
			case <-ch:
			case <-ctx.Done():
				return ctx.Err()
			}
		}
		app = kessoku.Provide(NewApp).Fn()(databaseService, cacheService, messagingService)
		return nil
	})
	eg.Go(func() error {
		cacheService = kessoku.Async(kessoku.Provide(NewCacheService)).Fn()()
		close(cacheServiceCh)
		return nil
	})
	eg.Go(func() error {
		messagingService = kessoku.Async(kessoku.Provide(NewMessagingService)).Fn()()
		close(messagingServiceCh)
		return nil
	})
	if err := eg.Wait(); err != nil {
		return nil, err
	}
	return app, nil
}
