// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"context"
	"github.com/mazrean/kessoku"
)

func InitializeApp(ctx context.Context) (*App, error) {
	config := kessoku.Provide(NewConfig).Fn()()
	var err error
	database, err := kessoku.Async(kessoku.Provide(NewDatabase)).Fn()(config)
	if err != nil {
		var zero *App
		return zero, err
	}
	var err0 error
	cache, err0 := kessoku.Async(kessoku.Provide(NewCache)).Fn()(database)
	if err0 != nil {
		var zero *App
		return zero, err0
	}
	app := kessoku.Provide(NewApp).Fn()(cache)
	return app, nil
}
