// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"context"
	"github.com/mazrean/kessoku"
	"golang.org/x/sync/errgroup"
)

func InitializeComplexApp(ctx context.Context) *App {
	v0 := kessoku.Provide(NewConfig).Fn()()
	v1 := kessoku.Async(kessoku.Provide(NewMessagingService)).Fn()(v0)
	v2 := kessoku.Async(kessoku.Provide(NewDatabaseService)).Fn()(v0)
	v4 := kessoku.Async(kessoku.Provide(NewUserService)).Fn()(v2)
	v3 := kessoku.Async(kessoku.Provide(NewCacheService)).Fn()(v0)
	v5 := kessoku.Async(kessoku.Provide(NewSessionService)).Fn()(v3)
	v6 := kessoku.Async(kessoku.Provide(NewNotificationService)).Fn()(v4, v5, v1)
	v7 := kessoku.Provide(NewComplexApp).Fn()(v6)
	return v7
}
