// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"github.com/mazrean/kessoku"
	"golang.org/x/sync/errgroup"
)

func InitializeComplexApp() *App {
	var (
		config              *Config
		configCh            = make(chan struct{})
		messagingService    *MessagingService
		databaseService     *DatabaseService
		cacheService        *CacheService
		userService         *UserService
		userServiceCh       = make(chan struct{})
		sessionService      *SessionService
		sessionServiceCh    = make(chan struct{})
		notificationService *NotificationService
		app                 *App
	)
	eg := &errgroup.Group{}
	eg.Go(func() error {
		<-configCh
		databaseService = kessoku.Async(kessoku.Provide(NewDatabaseService)).Fn()(config)
		userService = kessoku.Async(kessoku.Provide(NewUserService)).Fn()(databaseService)
		close(userServiceCh)
		return nil
	})
	eg.Go(func() error {
		<-configCh
		cacheService = kessoku.Async(kessoku.Provide(NewCacheService)).Fn()(config)
		sessionService = kessoku.Async(kessoku.Provide(NewSessionService)).Fn()(cacheService)
		close(sessionServiceCh)
		return nil
	})
	eg.Go(func() error {
		config = kessoku.Provide(NewConfig).Fn()()
		close(configCh)
		messagingService = kessoku.Async(kessoku.Provide(NewMessagingService)).Fn()(config)
		for _, ch := range []<-chan struct{}{userServiceCh, sessionServiceCh} {
			<-ch
		}
		notificationService = kessoku.Async(kessoku.Provide(NewNotificationService)).Fn()(userService, sessionService, messagingService)
		app = kessoku.Provide(NewComplexApp).Fn()(notificationService)
		return nil
	})
	eg.Wait()
	return app
}
