// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeApp() *App {
	fn := kessoku.Provide(NewEventHandler).Fn()()
	app := kessoku.Provide(NewApp).Fn()(fn)
	return app
}
