// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"github.com/mazrean/kessoku"
	"github.com/mazrean/kessoku/examples/cross_package/providers"
)

func InitializeCrossPackageService() *providers.ExternalService {
	ctx := kessoku.Provide(NewContext).Fn()()
	apikey := kessoku.Provide(NewAPIKey).Fn()()
	externalConfig := kessoku.Provide(providers.NewExternalConfig).Fn()(apikey)
	externalService := kessoku.Provide(providers.NewExternalService).Fn()(ctx, externalConfig)
	return externalService
}
