// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"github.com/mazrean/kessoku"
	"context"
	"github.com/mazrean/kessoku/examples/cross_package/providers"
)

func InitializeCrossPackageService(ctx context.Context, apikey providers.APIKey) *providers.ExternalService {
	v0 := kessoku.Provide(providers.NewExternalConfig).Fn()(apikey)
	v1 := kessoku.Provide(providers.NewExternalService).Fn()(ctx, v0)
	return v1
}
