// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"github.com/mazrean/kessoku"
	"github.com/mazrean/kessoku/internal/kessoku/testdata/dot_import_set/setpkg"
)

func InitializeService() *Service {
	config := kessoku.Provide(setpkg.NewConfig).Fn()()
	service := kessoku.Provide(NewService).Fn()(config)
	return service
}
