// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"github.com/mazrean/kessoku"
	"github.com/mazrean/kessoku/internal/kessoku/testdata/external_set_local_types/pkga"
)

func InitializeResult() *pkga.Result {
	result := kessoku.Provide(func() *pkga.Result {
		type pair struct{ a, b int }
		p := pair{1, 2}
		anon := struct {
			pkga.Base
			n int
		}{pkga.Base{ID: 3}, 4}
		return &pkga.Result{Sum: p.a + p.b + anon.ID + anon.n}
	}).Fn()()
	return result
}
