// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"github.com/mazrean/kessoku"
	"github.com/mazrean/kessoku/internal/kessoku/testdata/external_set_non_set_call/pkga"
)

func InitializeA() *pkga.A {
	a := kessoku.Provide(pkga.NewA).Fn()()
	return a
}
