// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeService() *Service {
	config := kessoku.Provide(NewConfig).Fn()()
	database, _ := kessoku.Provide(NewDatabase).Fn()(config)
	service := kessoku.Provide(NewService).Fn()(database)
	return service
}
