// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"github.com/mazrean/kessoku"
	"github.com/mazrean/kessoku/internal/kessoku/testdata/external_set_nested/pkga"
	"github.com/mazrean/kessoku/internal/kessoku/testdata/external_set_nested/pkgc"
)

func InitializeLabel() pkga.Label {
	c := kessoku.Provide(pkgc.NewC).Fn()()
	a := kessoku.Provide(pkga.NewPrefixed).Fn()(c)
	label := kessoku.Provide(func(a *pkga.A) pkga.Label {
		l := pkga.A{Name: pkga.Prefix + a.Name}
		return pkga.Label(l.Name)
	}).Fn()(a)
	return label
}
