// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeApp() *App {
	db, cleanup := kessoku.Provide(NewDB).Fn()()
	defer cleanup()
	cache, cleanup0 := kessoku.Provide(NewCache).Fn()()
	defer cleanup0()
	app := kessoku.Provide(NewApp).Fn()(db, cache)
	return app
}
