// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"github.com/mazrean/kessoku"
	"io"
	"os"
)

func InitializeService() *Service {
	file := kessoku.Bind[io.Writer](kessoku.Value(os.Stdout)).Fn()()
	service := kessoku.Provide(NewService).Fn()(file)
	return service
}
