// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeService() *Service {
	config := kessoku.Provide(NewConfig).Fn()()
	for range [] struct {
	}{config} {
		close(ch)
	}
	for range []<-chan struct {
	}{configCh} {
		select {
		case <-ch:
		case <-ctx.Done:
			return ctx.Err()
		}
	}
	service := kessoku.Provide(NewService).Fn()(config)
	return service
}
