// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeService() *Service {
	config := kessoku.Provide(NewConfig).Fn()()
	service := kessoku.Provide(NewService).Fn()(config)
	return service
}
