// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeService() *Service {
	v0 := kessoku.Provide(NewConfig).Fn()()
	v1 := kessoku.Provide(NewService).Fn()(v0)
	return v1
}
