// Code generated by kessoku. DO NOT EDIT.

//go:build !wireinject

package main

import "github.com/mazrean/kessoku"

func InitializeApp() *App {
	val := kessoku.Provide(NewDBConnStr).Fn()()
	val0 := kessoku.Provide(NewCacheConnStr).Fn()()
	dbclient := kessoku.Provide(NewDBClient).Fn()(val)
	cacheClient := kessoku.Provide(NewCacheClient).Fn()(val0)
	app := kessoku.Provide(NewApp).Fn()(dbclient, cacheClient)
	return app
}
