// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeDatabase() *Database {
	config := kessoku.Provide(NewConfig).Fn()()
	str := config.DBHost
	num := config.DBPort
	flag := config.Debug
	database := kessoku.Provide(NewDatabase).Fn()(str, num, flag)
	return database
}
