// Code generated by kessoku. DO NOT EDIT.

//go:build !wireinject

package main

import "github.com/mazrean/kessoku"

func InitializeRouter() *Router {
	routeMap := kessoku.Provide(NewRoutes).Fn()()
	handlerMap := kessoku.Provide(NewHandlers).Fn()()
	router := kessoku.Provide(NewRouter).Fn()(routeMap, handlerMap)
	return router
}
