// Code generated by kessoku. DO NOT EDIT.

//go:build !wireinject

package main

import "github.com/mazrean/kessoku"

func InitializeService() *Service {
	config, _ := kessoku.Provide(NewConfig).Fn()()
	service := kessoku.Provide(NewService).Fn()(config)
	return service
}
