// Code generated by kessoku. DO NOT EDIT.

//go:build !wireinject

package main

import "github.com/mazrean/kessoku"

func InitializeApp() *App {
	shutdownFunc := kessoku.Provide(NewShutdown).Fn()()
	commitFunc := kessoku.Provide(NewCommit).Fn()()
	app := kessoku.Provide(NewApp).Fn()(shutdownFunc, commitFunc)
	return app
}
