// Code generated by kessoku. DO NOT EDIT.

//go:build !wireinject

package main

import (
	"context"
	"github.com/mazrean/kessoku"
	"golang.org/x/sync/errgroup"
)

func InitializeService(ctx context.Context) (*Service, error) {
	var (
		errgroup0  *Errgroup
		database   *Database
		databaseCh = make(chan struct{})
		service    *Service
	)
	parentCtx := ctx
	ctx, cancel := context.WithCancel(ctx)
	eg, ctx := errgroup.WithContext(ctx)
	defer func() {
		cancel()
		_ = eg.Wait()
	}()
	eg.Go(func() error {
		var err error
		database, err = kessoku.Async(kessoku.Provide(NewDatabase)).Fn()()
		if err != nil {
			return err
		}
		close(databaseCh)
		return nil
	})
	var err0 error
	errgroup0, err0 = kessoku.Async(kessoku.Provide(NewErrgroup)).Fn()()
	if err0 != nil {
		var zero *Service
		return zero, err0
	}
	select {
	case <-databaseCh:
	case <-ctx.Done():
		var zero *Service
		return zero, context.Cause(ctx)
	}
	service = kessoku.Provide(NewService).Fn()(errgroup0, database)
	if err := eg.Wait(); err != nil {
		var zero *Service
		return zero, err
	}
	if err := parentCtx.Err(); err != nil {
		var zero *Service
		return zero, err
	}
	return service, nil
}
