// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeApp() *App {
	db := kessoku.Provide(NewDB).Fn()()
	app := kessoku.Provide(NewApp).Fn()(db)
	return app
}
