// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeApp() *App {
	val := kessoku.Provide(NewDB).Fn()()
	app := kessoku.Provide(NewApp).Fn()(val)
	return app
}
