// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"github.com/mazrean/kessoku"
	"github.com/mazrean/kessoku/internal/kessoku/testdata/external_set_shadowing/pkga"
)

func InitializeLabel() pkga.Label {
	config := kessoku.Provide(func() *pkga.Config {
		pkga0 := pkga.DefaultName
		return &pkga.Config{Name: pkga0}
	}).Fn()()
	label := kessoku.Provide(func(kessoku0 *pkga.Config) pkga.Label {
		return pkga.Label(kessoku0.Name + pkga.DefaultName)
	}).Fn()(config)
	return label
}
