// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"context"
	"github.com/mazrean/kessoku"
)

func InitializeService(ctx context.Context, apikey APIKey) *Service {
	config := kessoku.Provide(NewConfig).Fn()(apikey)
	service := kessoku.Provide(NewService).Fn()(ctx, config)
	return service
}
