// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"github.com/mazrean/kessoku"
	"github.com/mazrean/kessoku/internal/kessoku/testdata/external_set_import_alias/depimpl"
	"github.com/mazrean/kessoku/internal/kessoku/testdata/external_set_import_alias/setpkg"
)

func InitializeWrapper() *setpkg.Wrapper {
	d := kessoku.Provide(depimpl.NewD).Fn()()
	wrapper := kessoku.Provide(setpkg.NewWrapper).Fn()(d)
	return wrapper
}
