// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeAPIClient() *APIClient {
	duration := kessoku.Provide(NewTimeout).Fn()()
	client := kessoku.Provide(NewHTTPClient).Fn()(duration)
	apiclient := kessoku.Provide(NewAPIClient).Fn()(client)
	return apiclient
}
