// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeApp() (*App, error) {
	config := kessoku.Provide(NewConfig).Fn()()
	database, err := kessoku.Provide(NewDatabase).Fn()(config)
	if err != nil {
		var zero *App
		return zero, err
	}
	userService := kessoku.Provide(NewUserService).Fn()(database, config)
	app := kessoku.Provide(NewApp).Fn()(config, userService)
	return app, nil
}
