name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          direct_prompt: |
            Please review this pull request and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage

            Be constructive and helpful in your feedback.
          allowed_tools: |
            Bash(go test ./...)
            Bash(go test -v ./...)
            Bash(go build ./...)
            Bash(go build -o bin/kessoku ./cmd/kessoku)
            Bash(go run ./...)
            Bash(go fmt ./...)
            Bash(go generate ./...)
            Bash(go tool kessoku)
            Bash(go tool tools lint ./...)
            Bash(go tool tools apicompat)
            Read
            Glob
            Grep
        if: ${{ !contains(github.event.pull_request.labels, 'dependencies') }}
