// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/mazrean/kessoku"
	"golang.org/x/sync/errgroup"
)

func InitApp(ctx context.Context) string {
	var (
		db      *DB
		cache   *Cache
		cacheCh = make(chan struct{})
		str     string
	)
	eg := &errgroup.Group{}
	eg.Go(func() error {
		cache = kessoku.Async(kessoku.Provide(SlowCache)).Fn()()
		close(cacheCh)
		return nil
	})
	db = kessoku.Async(kessoku.Provide(SlowDB)).Fn()()
	<-cacheCh
	str = kessoku.Provide(func(db *DB, cache *Cache) string {
		return fmt.Sprintf("App running with %s and %s", db.Addr, cache.Addr)
	}).Fn()(db, cache)
	_ = eg.Wait()
	return str
}
