package kessoku

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"io"
	"slices"
	"strings"
)

const (
	// maxInjectorReturnValues represents the maximum number of return values for an injector function
	maxInjectorReturnValues = 2
)

func Generate(w io.Writer, filename string, metaData *MetaData, injectors []*Injector, varPool *VarPool) error {
	file := &ast.File{
		Name: ast.NewIdent(metaData.Package.Name),
	}

	// Generate injector function declarations.
	// Each injector gets a fresh snapshot of the file-level VarPool so that
	// local variable names (config, err, eg, ...) are allocated independently
	// per injector function.  The file-level varPool is still passed for any
	// import-alias allocations that may happen during code generation.
	var funcDecls []ast.Decl
	for _, injector := range injectors {
		injectorVarPool := varPool.Snapshot()
		funcDecl, err := generateInjectorDecl(metaData, injector, injectorVarPool, varPool)
		if err != nil {
			return fmt.Errorf("generate injector declaration for %s: %w", injector.Name, err)
		}

		funcDecls = append(funcDecls, funcDecl)
	}

	// Generate import declarations only for used imports
	usedImports := GetUsedImports(metaData.Imports)
	importSpecs := make([]*ast.ImportSpec, 0, len(usedImports))
	for path, imp := range usedImports {
		importSpecs = append(importSpecs, importSpec(imp, path))
	}
	slices.SortFunc(importSpecs, func(a, b *ast.ImportSpec) int {
		return strings.Compare(a.Path.Value, b.Path.Value)
	})
	importDecl := generateImportDecl(importSpecs)
	if importDecl != nil {
		file.Decls = append(file.Decls, importDecl)
	}

	// Add function declarations after imports
	file.Decls = append(file.Decls, funcDecls...)

	// Add DO NOT EDIT comment and build constraint so that the generated
	// *_band.go file is excluded when packages are loaded with -tags=wireinject
	// (e.g. by kessoku migrate).  Without this constraint, re-running migrate
	// after codegen fails with "InitXxx redeclared" because both the original
	// wire.go (//go:build wireinject) and this file declare the same injector.
	_, err := w.Write([]byte("// Code generated by kessoku. DO NOT EDIT.\n\n//go:build !wireinject\n\n"))
	if err != nil {
		return fmt.Errorf("write DO NOT EDIT comment: %w", err)
	}

	// Format and write the generated code
	err = format.Node(w, token.NewFileSet(), file)
	if err != nil {
		return fmt.Errorf("format generated code: %w", err)
	}

	return nil
}

// isContextType checks if a type is context.Context, including user-defined
// aliases such as `type Ctx = context.Context`.
func isContextType(t types.Type) bool {
	if named, ok := types.Unalias(t).(*types.Named); ok {
		if obj := named.Obj(); obj != nil && obj.Pkg() != nil {
			return obj.Pkg().Path() == contextPkgPath && obj.Name() == contextTypeName
		}
	}

	return false
}

// hasChainStmts determines if the injector contains InjectorChainStmt
// which requires errgroup for goroutine management
func hasChainStmts(injector *Injector) bool {
	for _, stmt := range injector.Stmts {
		if _, ok := stmt.(*InjectorChainStmt); ok {
			return true
		}
		// Also check for nested InjectorChainStmt within InjectorProviderCallStmt
		if providerStmt, ok := stmt.(*InjectorProviderCallStmt); ok {
			// Check if any nested statements contain chain statements
			_ = providerStmt // Provider call statements don't contain nested chain statements
		}
	}
	return false
}

// ensureImport returns the local name of the import for pkgPath, creating
// and registering it via varPool when missing, and marks it as used.
func ensureImport(imports map[string]*Import, varPool *VarPool, pkgPath, pkgName string) string {
	if imp, exists := imports[pkgPath]; exists {
		imp.IsUsed = true
		return imp.Name
	}

	name := varPool.GetName(pkgName)
	imports[pkgPath] = &Import{
		Name:          name,
		IsDefaultName: pkgName == name,
		IsUsed:        true,
	}

	return name
}

// generateAsyncInitialization creates errgroup and variable declarations for async execution.
// It returns the generated statements, the name of the parent context variable (if any), and any error.
// The parent context variable preserves the original ctx parameter before errgroup.WithContext shadows it,
// so that ctx.Err() can be checked after eg.Wait() to detect cancellation that completed before any error.
//
// For error-returning injectors it establishes the exit protocol of the
// generated code: a cancellable context wrapping the caller's context plus a
// deferred `cancel(); eg.Wait()` pair, so that every early return unblocks
// and joins all in-flight provider goroutines (no goroutine leaks, no
// abandoned channels).
//
// Injectors without an error return cannot observe provider failures (none of
// their providers return errors), so their generated code waits on completion
// channels unconditionally instead of selecting on context cancellation.
// This keeps them deadlock-free even when called with a cancelled context.
//
// localVarPool is used for local variable name allocation (eg, cancel, ctx, parentCtx);
// fileVarPool is used for import-alias allocation (errgroup, context) that must be
// unique across the entire output file.
func generateAsyncInitialization(pkg string, injector *Injector, localVarPool *VarPool, fileVarPool *VarPool, imports map[string]*Import) ([]ast.Stmt, string, error) {
	var stmts []ast.Stmt

	errgroupAlias := ensureImport(imports, fileVarPool, errgroupPkgPath, errgroupPkgName)
	// Reserve the errgroup alias in the per-injector pool so that a provider
	// returning a user type whose lowerCamel base name equals the alias (e.g.
	// *Errgroup → "errgroup") does not claim that name for its local variable,
	// which would shadow the package reference and cause a compile error.
	localVarPool.Reserve(errgroupAlias)

	// Find context parameter name if available
	var ctxParamName string
	for _, arg := range injector.Args {
		if isContextType(arg.Type) {
			ctxParamName = arg.Param.Name(localVarPool)
			break
		}
	}

	// Generate variable declarations for async access
	varSpecs, err := generateVariableSpecs(pkg, injector, localVarPool, fileVarPool, imports)
	if err != nil {
		return nil, "", fmt.Errorf("generate variable declarations: %w", err)
	}

	stmts = append(stmts, &ast.DeclStmt{
		Decl: &ast.GenDecl{
			Tok:   token.VAR,
			Specs: varSpecs,
		},
	})

	injector.asyncEgName = localVarPool.GetName("eg")

	if !injector.IsReturnError {
		// Unconditional channel waits: no cancellable context needed.
		injector.asyncCtxName = ""
		stmts = append(stmts, generateErrGroupDeclaration(injector.asyncEgName, "", errgroupAlias))

		return stmts, "", nil
	}

	contextAlias := ensureImport(imports, fileVarPool, contextPkgPath, contextPkgName)
	injector.asyncContextAlias = contextAlias
	injector.asyncCancelName = localVarPool.GetName("cancel")

	// ctx, cancel := context.WithCancel(ctx)
	// (falls back to context.Background() when the injector has no context
	// parameter; async injectors normally receive one automatically)
	//
	// Save the original ctx before context.WithCancel shadows the name so that
	// we can check parentCtx.Err() after eg.Wait() (BUG-06: a goroutine may
	// complete via the channel select arm at the exact instant the caller's
	// deadline fires; eg.Wait() then returns nil while parentCtx is cancelled).
	var parentCtxName string
	var parentCtxExpr ast.Expr
	if ctxParamName != "" {
		injector.asyncCtxName = ctxParamName
		parentCtxName = localVarPool.GetName("parentCtx")
		// parentCtx := ctx
		stmts = append(stmts, &ast.AssignStmt{
			Lhs: []ast.Expr{ast.NewIdent(parentCtxName)},
			Tok: token.DEFINE,
			Rhs: []ast.Expr{ast.NewIdent(ctxParamName)},
		})
		parentCtxExpr = ast.NewIdent(ctxParamName)
	} else {
		injector.asyncCtxName = localVarPool.GetName("ctx")
		parentCtxExpr = &ast.CallExpr{
			Fun: &ast.SelectorExpr{
				X:   ast.NewIdent(contextAlias),
				Sel: ast.NewIdent("Background"),
			},
		}
	}

	stmts = append(stmts, &ast.AssignStmt{
		Lhs: []ast.Expr{
			ast.NewIdent(injector.asyncCtxName),
			ast.NewIdent(injector.asyncCancelName),
		},
		Tok: token.DEFINE,
		Rhs: []ast.Expr{
			&ast.CallExpr{
				Fun: &ast.SelectorExpr{
					X:   ast.NewIdent(contextAlias),
					Sel: ast.NewIdent("WithCancel"),
				},
				Args: []ast.Expr{parentCtxExpr},
			},
		},
	})

	stmts = append(stmts, generateErrGroupDeclaration(injector.asyncEgName, injector.asyncCtxName, errgroupAlias))

	// defer func() { cancel(); _ = eg.Wait() }()
	// Guarantees that any return path unblocks and joins provider goroutines.
	stmts = append(stmts, &ast.DeferStmt{
		Call: &ast.CallExpr{
			Fun: &ast.FuncLit{
				Type: &ast.FuncType{Params: &ast.FieldList{}},
				Body: &ast.BlockStmt{
					List: []ast.Stmt{
						&ast.ExprStmt{
							X: &ast.CallExpr{
								Fun: ast.NewIdent(injector.asyncCancelName),
							},
						},
						&ast.AssignStmt{
							Lhs: []ast.Expr{ast.NewIdent("_")},
							Tok: token.ASSIGN,
							Rhs: []ast.Expr{
								&ast.CallExpr{
									Fun: &ast.SelectorExpr{
										X:   ast.NewIdent(injector.asyncEgName),
										Sel: ast.NewIdent("Wait"),
									},
								},
							},
						},
					},
				},
			},
		},
	})

	return stmts, parentCtxName, nil
}

// generateErrGroupDeclaration creates the errgroup variable declaration.
// ctxName is the name of the context variable to derive from (empty string
// when the errgroup should not be bound to a context).
func generateErrGroupDeclaration(egName, ctxName, errgroupAlias string) *ast.AssignStmt {
	if ctxName != "" {
		return &ast.AssignStmt{
			Lhs: []ast.Expr{
				ast.NewIdent(egName),
				ast.NewIdent(ctxName),
			},
			Tok: token.DEFINE,
			Rhs: []ast.Expr{
				&ast.CallExpr{
					Fun: &ast.SelectorExpr{
						X:   ast.NewIdent(errgroupAlias),
						Sel: ast.NewIdent("WithContext"),
					},
					Args: []ast.Expr{ast.NewIdent(ctxName)},
				},
			},
		}
	}

	return &ast.AssignStmt{
		Lhs: []ast.Expr{ast.NewIdent(egName)},
		Tok: token.DEFINE,
		Rhs: []ast.Expr{
			&ast.UnaryExpr{
				Op: token.AND,
				X: &ast.CompositeLit{
					Type: &ast.SelectorExpr{
						X:   ast.NewIdent(errgroupAlias),
						Sel: ast.NewIdent("Group"),
					},
				},
			},
		},
	}
}

// generateVariableSpecs creates variable declarations for async access.
// localVarPool is used for local variable name allocation; fileVarPool is used
// for import-alias allocation in createASTTypeExpr.
func generateVariableSpecs(pkg string, injector *Injector, localVarPool *VarPool, fileVarPool *VarPool, imports map[string]*Import) ([]ast.Spec, error) {
	var specs []ast.Spec

	for _, param := range injector.Vars {
		paramName := param.Name(localVarPool)
		if paramName == "_" {
			continue
		}

		// Mark imports used by this var-defined parameter as used
		for _, imp := range param.ReferencedImports {
			imp.IsUsed = true
		}

		typeExpr, err := createASTTypeExpr(pkg, param.Type(), fileVarPool, imports)
		if err != nil {
			return nil, fmt.Errorf("create AST type expression for %s: %w", paramName, err)
		}

		specs = append(specs, &ast.ValueSpec{
			Names: []*ast.Ident{ast.NewIdent(paramName)},
			Type:  typeExpr,
		})

		if !param.WithChannel() {
			continue
		}

		specs = append(specs, &ast.ValueSpec{
			Names: []*ast.Ident{ast.NewIdent(param.ChannelName(localVarPool))},
			Values: []ast.Expr{
				&ast.CallExpr{
					Fun: ast.NewIdent("make"),
					Args: []ast.Expr{
						&ast.ChanType{
							Dir:   ast.SEND | ast.RECV,
							Value: ast.NewIdent("struct{}"),
						},
					},
				},
			},
		})
	}

	return specs, nil
}

// generateAsyncWaitStatements creates errgroup wait statements.
// parentCtxName is the variable holding the original context before errgroup.WithContext shadowed it;
// if non-empty and the injector returns an error, a ctx.Err() guard is emitted after eg.Wait()
// to catch cancellations that raced past the goroutine channel-selects.
func generateAsyncWaitStatements(injector *Injector, parentCtxName string, returnErrStmts func(ast.Expr) []ast.Stmt) []ast.Stmt {
	if injector.IsReturnError && returnErrStmts != nil {
		errIdent := ast.NewIdent("err")

		stmts := []ast.Stmt{
			&ast.IfStmt{
				Init: &ast.AssignStmt{
					Lhs: []ast.Expr{errIdent},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun: &ast.SelectorExpr{
								X:   ast.NewIdent(injector.egName()),
								Sel: ast.NewIdent("Wait"),
							},
						},
					},
				},
				Cond: &ast.BinaryExpr{
					X:  errIdent,
					Op: token.NEQ,
					Y:  ast.NewIdent("nil"),
				},
				Body: &ast.BlockStmt{
					List: returnErrStmts(errIdent),
				},
			},
		}

		// Guard against the race where goroutines completed via the channel case of a select
		// just as the caller's context deadline expired.  eg.Wait() returns nil in this case
		// but the parent context is already cancelled, so we must surface the cancellation error.
		if parentCtxName != "" {
			ctxErrIdent := ast.NewIdent("err")
			stmts = append(stmts, &ast.IfStmt{
				Init: &ast.AssignStmt{
					Lhs: []ast.Expr{ctxErrIdent},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun: &ast.SelectorExpr{
								X:   ast.NewIdent(parentCtxName),
								Sel: ast.NewIdent("Err"),
							},
						},
					},
				},
				Cond: &ast.BinaryExpr{
					X:  ctxErrIdent,
					Op: token.NEQ,
					Y:  ast.NewIdent("nil"),
				},
				Body: &ast.BlockStmt{
					List: returnErrStmts(ctxErrIdent),
				},
			})
		}

		return stmts
	}

	return []ast.Stmt{
		&ast.AssignStmt{
			Lhs: []ast.Expr{ast.NewIdent("_")},
			Tok: token.ASSIGN,
			Rhs: []ast.Expr{
				&ast.CallExpr{
					Fun: &ast.SelectorExpr{
						X:   ast.NewIdent(injector.egName()),
						Sel: ast.NewIdent("Wait"),
					},
				},
			},
		},
	}
}

func generateImportDecl(imporSpecs []*ast.ImportSpec) *ast.GenDecl {
	specs := make([]ast.Spec, 0, len(imporSpecs))
	for _, importSpec := range imporSpecs {
		specs = append(specs, importSpec)
	}
	if len(specs) == 0 {
		return nil
	}

	return &ast.GenDecl{
		Tok:   token.IMPORT,
		Specs: specs,
	}
}

// generateInjectorDecl generates a function declaration for an injector.
// localVarPool is a per-injector pool used for local variable name allocation
// (params, err, eg, channels, …).  fileVarPool is the file-scoped pool used
// for any new import-alias allocation that may be needed during generation.
func generateInjectorDecl(metaData *MetaData, injector *Injector, localVarPool *VarPool, fileVarPool *VarPool) (ast.Decl, error) {
	paramFields := make([]*ast.Field, 0, len(injector.Args)+1)

	// Add parameters
	for _, arg := range injector.Args {
		if arg != nil && arg.ASTTypeExpr != nil && arg.Param != nil {
			// Mark imports used by argument types as used since they appear in function signature
			for _, imp := range arg.Param.ReferencedImports {
				imp.IsUsed = true
			}
			paramFields = append(paramFields, &ast.Field{
				Names: []*ast.Ident{ast.NewIdent(arg.Param.Name(localVarPool))},
				Type:  arg.ASTTypeExpr,
			})
		}
	}

	// Return type - will be set in Results field
	resultsFields := make([]*ast.Field, 0, maxInjectorReturnValues)
	if injector.Return != nil && injector.Return.Return != nil && injector.Return.Return.ASTTypeExpr != nil {
		// Mark imports used by return types as used since they appear in function signature
		if injector.Return.Param != nil {
			for _, imp := range injector.Return.Param.ReferencedImports {
				imp.IsUsed = true
			}
		}
		resultsFields = append(resultsFields, &ast.Field{
			Type: injector.Return.Return.ASTTypeExpr,
		})
	}
	if injector.IsReturnError {
		resultsFields = append(resultsFields, &ast.Field{
			Type: &ast.Ident{Name: "error"},
		})
	}

	var params *ast.FieldList
	if len(paramFields) > 0 {
		// Validate that all param fields have non-nil Type
		validParams := make([]*ast.Field, 0, len(paramFields))
		for _, field := range paramFields {
			if field != nil && field.Type != nil {
				validParams = append(validParams, field)
			}
		}
		if len(validParams) > 0 {
			params = &ast.FieldList{
				List: validParams,
			}
		}
	}

	var results *ast.FieldList
	if len(resultsFields) > 0 {
		// Validate that all result fields have non-nil Type
		validResults := make([]*ast.Field, 0, len(resultsFields))
		for _, field := range resultsFields {
			if field != nil && field.Type != nil {
				validResults = append(validResults, field)
			}
		}
		if len(validResults) > 0 {
			results = &ast.FieldList{
				List: validResults,
			}
		}
	}

	funcType := &ast.FuncType{
		Params:  params,
		Results: results,
	}

	stmts, err := generateStmts(localVarPool, fileVarPool, metaData.Package.Path, injector, metaData.Imports)
	if err != nil {
		return nil, fmt.Errorf("generate statements: %w", err)
	}

	funcDecl := &ast.FuncDecl{
		Name: ast.NewIdent(injector.Name),
		Type: funcType,
		Body: &ast.BlockStmt{
			List: stmts,
		},
	}

	return funcDecl, nil
}

// generateStmts generates statements with parallel execution support using errgroup.
// localVarPool is the per-injector pool for local variable names; fileVarPool is
// the file-scoped pool used for any import-alias allocation during generation.
func generateStmts(localVarPool *VarPool, fileVarPool *VarPool, pkg string, injector *Injector, imports map[string]*Import) ([]ast.Stmt, error) {
	var stmts []ast.Stmt

	hasChains := hasChainStmts(injector)

	// parentCtxName is the variable holding the original ctx before errgroup.WithContext shadows it.
	var parentCtxName string

	// Initialize async components if needed
	if hasChains {
		asyncStmts, pCtx, err := generateAsyncInitialization(pkg, injector, localVarPool, fileVarPool, imports)
		if err != nil {
			return nil, fmt.Errorf("generate async initialization: %w", err)
		}

		stmts = append(stmts, asyncStmts...)
		parentCtxName = pCtx
	}

	var returnErrStmts func(ast.Expr) []ast.Stmt
	switch {
	case !injector.IsReturnError:
		returnErrStmts = nil
	case injector.Return != nil && injector.Return.Return != nil && injector.Return.Return.ASTTypeExpr != nil:
		returnErrStmts = func(errExpr ast.Expr) []ast.Stmt {
			return []ast.Stmt{
				&ast.DeclStmt{
					Decl: &ast.GenDecl{
						Tok: token.VAR,
						Specs: []ast.Spec{
							&ast.ValueSpec{
								Names: []*ast.Ident{ast.NewIdent("zero")},
								Type:  injector.Return.Return.ASTTypeExpr,
							},
						},
					},
				},
				&ast.ReturnStmt{
					Results: []ast.Expr{ast.NewIdent("zero"), errExpr},
				},
			}
		}
	default:
		returnErrStmts = func(errExpr ast.Expr) []ast.Stmt {
			return []ast.Stmt{
				&ast.ReturnStmt{
					Results: []ast.Expr{errExpr},
				},
			}
		}
	}

	// Process statements and collect completion channels
	for _, stmt := range injector.Stmts {
		newStmts, _ := stmt.Stmt(localVarPool, injector, returnErrStmts, false)
		stmts = append(stmts, newStmts...)
	}

	// Add async completion handling
	if hasChains {
		waitStmts := generateAsyncWaitStatements(injector, parentCtxName, returnErrStmts)
		stmts = append(stmts, waitStmts...)
	}

	// Add return statement
	returnExprs := make([]ast.Expr, 0, maxInjectorReturnValues)
	if injector.Return != nil && injector.Return.Param != nil {
		returnExprs = append(returnExprs, ast.NewIdent(injector.Return.Param.Name(localVarPool)))
	}
	if injector.IsReturnError {
		returnExprs = append(returnExprs, ast.NewIdent("nil"))
	}
	if len(returnExprs) > 0 {
		stmts = append(stmts, &ast.ReturnStmt{
			Results: returnExprs,
		})
	}

	return stmts, nil
}

func (stmt *InjectorProviderCallStmt) Stmt(varPool *VarPool, injector *Injector, returnErrStmts func(ast.Expr) []ast.Stmt, inChain bool) ([]ast.Stmt, []string) {
	var stmts []ast.Stmt

	// Add channel synchronization for async scenarios
	hasChains := hasChainStmts(injector)
	if hasChains {
		waitStmt := stmt.generateChannelWaitStatement(varPool, injector, returnErrStmts, inChain)
		if waitStmt != nil {
			stmts = append(stmts, waitStmt)
		}
	}

	// Generate provider function call
	args := stmt.buildArguments(varPool)
	rhs := stmt.buildProviderCall(args)

	// Generate assignment statement
	lhs := stmt.buildLhsExpressions(varPool)

	var errorHandleStmt ast.Stmt
	if stmt.Provider.IsReturnError {
		errIdentName := varPool.GetName("err")
		errIdent := ast.NewIdent(errIdentName)
		lhs = append(lhs, errIdent)

		// Use the provider's exact error return type for the var declaration.
		// When a provider returns a concrete type (e.g. *MyError) rather than
		// the error interface, declaring `var err error` would cause nil-interface
		// false positives: a nil *MyError assigned to an error interface becomes
		// non-nil. Using the concrete type avoids that pitfall.
		errTypeExpr := stmt.Provider.ErrorTypeExpr
		if errTypeExpr == nil {
			// Fallback: should not happen in practice, but keep behaviour safe.
			errTypeExpr = ast.NewIdent("error")
		}

		stmts = append(stmts, &ast.DeclStmt{
			Decl: &ast.GenDecl{
				Tok: token.VAR,
				Specs: []ast.Spec{
					&ast.ValueSpec{
						Names: []*ast.Ident{errIdent},
						Type:  errTypeExpr,
					},
				},
			},
		})

		errorHandleStmt = stmt.buildErrorHandlingStatement(errIdent, injector, returnErrStmts)
	}

	// When Returns is empty and IsReturnError is true, the only LHS variable is the
	// pre-declared "err". Use plain assignment (=) instead of short var decl (:=).
	onlyErrOnLhs := stmt.Provider.IsReturnError && len(stmt.Returns) == 0
	assignStmt := stmt.buildAssignmentStatement(lhs, rhs, hasChains || onlyErrOnLhs)
	stmts = append(stmts, assignStmt)

	if errorHandleStmt != nil {
		stmts = append(stmts, errorHandleStmt)
	}

	// Add channel cleanup for async scenarios
	if hasChains {
		closeStmt := stmt.generateChannelCloseStatement(varPool)
		if closeStmt != nil {
			stmts = append(stmts, closeStmt)
		}
	}

	for _, reference := range stmt.Provider.ReferencedImports {
		reference.IsUsed = true // Mark imports used by this provider as used
	}

	return stmts, nil
}

func (stmt *InjectorProviderCallStmt) channelsWait(channels []ast.Expr, injector *Injector, returnErrStmts func(ast.Expr) []ast.Stmt, inChain bool) ast.Stmt {
	if len(channels) == 1 {
		// Single channel case
		return stmt.buildWaitStatement(injector, channels[0], returnErrStmts, inChain)
	}

	return &ast.RangeStmt{
		Tok:   token.DEFINE,
		Key:   ast.NewIdent("_"),
		Value: ast.NewIdent("ch"),
		X: &ast.CompositeLit{
			Type: &ast.ArrayType{
				Elt: &ast.ChanType{
					Dir:   ast.RECV,
					Value: ast.NewIdent("struct{}"),
				},
			},
			Elts: channels,
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				stmt.buildWaitStatement(injector, ast.NewIdent("ch"), returnErrStmts, inChain),
			},
		},
	}
}

// buildWaitStatement emits the wait for a dependency's completion channel.
//
// When the injector has no cancellable context (non-error-returning builds)
// the wait is an unconditional receive: none of the providers can fail, so
// every channel is guaranteed to be closed and selecting on context
// cancellation would only introduce paths that leave waiters stuck or return
// silent zero values.
//
// Inside errgroup goroutines the ctx.Done() branch returns ctx.Err() into the
// errgroup. On the main goroutine it consults eg.Wait() first so the actual
// provider failure is returned to the caller instead of a derived
// context.Canceled.
func (stmt *InjectorProviderCallStmt) buildWaitStatement(injector *Injector, channel ast.Expr, returnErrStmts func(ast.Expr) []ast.Stmt, inChain bool) ast.Stmt {
	ctxName := injector.asyncCtxName
	contextAlias := injector.asyncContextAlias
	if contextAlias == "" {
		contextAlias = contextPkgName
	}
	if ctxName == "" || returnErrStmts == nil {
		return &ast.ExprStmt{
			X: &ast.UnaryExpr{
				Op: token.ARROW,
				X:  channel,
			},
		}
	}

	return &ast.SelectStmt{
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.CaseClause{
					List: []ast.Expr{
						&ast.UnaryExpr{
							Op: token.ARROW,
							X:  channel,
						},
					},
					Body: []ast.Stmt{},
				},
				&ast.CaseClause{
					List: []ast.Expr{
						&ast.UnaryExpr{
							Op: token.ARROW,
							X: &ast.CallExpr{
								Fun: &ast.SelectorExpr{
									X:   ast.NewIdent(ctxName),
									Sel: ast.NewIdent("Done"),
								},
							},
						},
					},
					Body: returnErrStmts(&ast.CallExpr{
						Fun: &ast.SelectorExpr{
							X:   ast.NewIdent(contextAlias),
							Sel: ast.NewIdent("Cause"),
						},
						Args: []ast.Expr{ast.NewIdent(ctxName)},
					}),
				},
			},
		},
	}
}

func (stmt *InjectorProviderCallStmt) channelsClose(channels []ast.Expr) ast.Stmt {
	if len(channels) == 1 {
		return &ast.ExprStmt{
			X: &ast.CallExpr{
				Fun: ast.NewIdent("close"),
				Args: []ast.Expr{
					channels[0],
				},
			},
		}
	}

	/*
		ast of:
		for _, ch := range []<-chan struct{}{v1, v2, v3} {
			close(ch)
		}
	*/
	return &ast.RangeStmt{
		Tok:   token.DEFINE,
		Key:   ast.NewIdent("_"),
		Value: ast.NewIdent("ch"),
		X: &ast.CompositeLit{
			Type: &ast.ArrayType{
				Elt: &ast.ChanType{
					Dir:   ast.SEND,
					Value: ast.NewIdent("struct{}"),
				},
			},
			Elts: channels,
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.ExprStmt{
					X: &ast.CallExpr{
						Fun: ast.NewIdent("close"),
						Args: []ast.Expr{
							ast.NewIdent("ch"),
						},
					},
				},
			},
		},
	}
}

func chainReturnErrStmts(errExpr ast.Expr) []ast.Stmt {
	return []ast.Stmt{
		&ast.ReturnStmt{
			Results: []ast.Expr{errExpr},
		},
	}
}

func (stmt *InjectorChainStmt) Stmt(varPool *VarPool, injector *Injector, _ func(ast.Expr) []ast.Stmt, _ bool) ([]ast.Stmt, []string) {
	var imports []string
	var stmts []ast.Stmt

	// Providers of non-error-returning injectors cannot fail, so their
	// goroutines wait on dependency channels unconditionally (nil
	// returnErrStmts) instead of racing against context cancellation.
	chainErrStmts := chainReturnErrStmts
	if !injector.IsReturnError {
		chainErrStmts = nil
	}

	// Generate statements for this chain
	for _, chainStmt := range stmt.Statements {
		chainStmts, chainImports := chainStmt.Stmt(varPool, injector, chainErrStmts, true)
		stmts = append(stmts, chainStmts...)
		imports = append(imports, chainImports...)
	}

	stmts = append(stmts, &ast.ReturnStmt{
		Results: []ast.Expr{ast.NewIdent("nil")},
	})

	// Always wrap in eg.Go() call as expected by tests
	return []ast.Stmt{
		&ast.ExprStmt{
			X: &ast.CallExpr{
				Fun: &ast.SelectorExpr{
					X:   ast.NewIdent(injector.egName()),
					Sel: ast.NewIdent("Go"),
				},
				Args: []ast.Expr{
					&ast.FuncLit{
						Type: &ast.FuncType{
							Params: nil, // Empty parameter list
							Results: &ast.FieldList{
								List: []*ast.Field{
									{
										Type: &ast.Ident{Name: "error"},
									},
								},
							},
						},
						Body: &ast.BlockStmt{
							List: stmts,
						},
					},
				},
			},
		},
	}, imports
}

// buildLhsExpressions builds the left-hand side expressions for assignment
func (stmt *InjectorProviderCallStmt) buildLhsExpressions(varPool *VarPool) []ast.Expr {
	var lhs []ast.Expr

	// Add output parameters, but avoid duplicates for multi-type providers
	seenParams := make(map[*InjectorParam]bool)
	for _, param := range stmt.Returns {
		if !seenParams[param] {
			paramName := param.Name(varPool)
			lhs = append(lhs, ast.NewIdent(paramName))
			seenParams[param] = true
		}
	}

	return lhs
}

// buildArguments builds the arguments for the provider call
func (stmt *InjectorProviderCallStmt) buildArguments(varPool *VarPool) []ast.Expr {
	var args []ast.Expr

	// Add input parameters
	for _, arg := range stmt.Arguments {
		args = append(args, ast.NewIdent(arg.Param.Name(varPool)))
	}

	return args
}

// buildProviderCall builds the provider function call expression
func (stmt *InjectorProviderCallStmt) buildProviderCall(args []ast.Expr) []ast.Expr {
	callExpr := &ast.CallExpr{
		Fun: &ast.CallExpr{
			Fun: &ast.SelectorExpr{
				X:   stmt.Provider.ASTExpr,
				Sel: ast.NewIdent("Fn"),
			},
		},
		Args: args,
	}

	// Variadic providers receive the last dependency as a slice that must be
	// expanded at the call site: fn(a, opts...).
	// When the variadic last parameter was matched via an element-type provider
	// (e.g. NewOption() Option satisfying ...Option), the value is already a
	// plain element — no spread is needed.
	if stmt.Provider.IsVariadic && !stmt.VariadicElemMatch && len(args) > 0 {
		callExpr.Ellipsis = token.Pos(1)
	}

	return []ast.Expr{callExpr}
}

// buildAssignmentStatement builds the assignment statement
func (stmt *InjectorProviderCallStmt) buildAssignmentStatement(lhs, rhs []ast.Expr, hasChains bool) ast.Stmt {
	tokenType := token.DEFINE
	if hasChains {
		tokenType = token.ASSIGN
	}

	return &ast.AssignStmt{
		Lhs: lhs,
		Tok: tokenType,
		Rhs: rhs,
	}
}

// buildErrorHandlingStatement builds error handling statements.
//
// When the injector uses an errgroup context (asyncCtxName != ""), a context
// cancellation triggered by a goroutine failure must surface the root-cause
// error rather than context.Canceled. We emit:
//
//	if err != nil {
//	    if cause := context.Cause(ctx); cause != nil {
//	        return zero, cause
//	    }
//	    return zero, err
//	}
//
// Without the context.Cause check the caller would observe context.Canceled
// while the real error from the errgroup goroutine is silently dropped.
func (stmt *InjectorProviderCallStmt) buildErrorHandlingStatement(errIdent *ast.Ident, injector *Injector, returnErrStmts func(ast.Expr) []ast.Stmt) ast.Stmt {
	if returnErrStmts == nil {
		return &ast.EmptyStmt{}
	}

	var bodyStmts []ast.Stmt

	// When an errgroup cancellable context exists, check context.Cause(ctx)
	// first so that the root-cause error from a goroutine failure is returned
	// instead of the derivative context.Canceled that the provider observed.
	ctxName := injector.asyncCtxName
	contextAlias := injector.asyncContextAlias
	if ctxName != "" {
		if contextAlias == "" {
			contextAlias = contextPkgName
		}

		causeIdent := ast.NewIdent("cause")
		causeCall := &ast.CallExpr{
			Fun: &ast.SelectorExpr{
				X:   ast.NewIdent(contextAlias),
				Sel: ast.NewIdent("Cause"),
			},
			Args: []ast.Expr{ast.NewIdent(ctxName)},
		}

		bodyStmts = append(bodyStmts, &ast.IfStmt{
			Init: &ast.AssignStmt{
				Lhs: []ast.Expr{causeIdent},
				Tok: token.DEFINE,
				Rhs: []ast.Expr{causeCall},
			},
			Cond: &ast.BinaryExpr{
				X:  causeIdent,
				Op: token.NEQ,
				Y:  ast.NewIdent("nil"),
			},
			Body: &ast.BlockStmt{
				List: returnErrStmts(causeIdent),
			},
		})
	}

	bodyStmts = append(bodyStmts, returnErrStmts(errIdent)...)

	return &ast.IfStmt{
		Cond: &ast.BinaryExpr{
			X:  errIdent,
			Op: token.NEQ,
			Y:  ast.NewIdent("nil"),
		},
		Body: &ast.BlockStmt{
			List: bodyStmts,
		},
	}
}

// generateChannelWaitStatement generates channel wait statements for async coordination
func (stmt *InjectorProviderCallStmt) generateChannelWaitStatement(varPool *VarPool, injector *Injector, returnErrStmts func(ast.Expr) []ast.Stmt, inChain bool) ast.Stmt {
	var channels []ast.Expr

	// Collect channels from dependencies
	for _, arg := range stmt.Arguments {
		if arg.IsWait && arg.Param.WithChannel() {
			channels = append(channels, ast.NewIdent(arg.Param.ChannelName(varPool)))
		}
	}

	if len(channels) == 0 {
		return nil
	}

	return stmt.channelsWait(channels, injector, returnErrStmts, inChain)
}

// generateChannelCloseStatement generates channel close statements for async coordination
func (stmt *InjectorProviderCallStmt) generateChannelCloseStatement(varPool *VarPool) ast.Stmt {
	var channels []ast.Expr

	// Collect channels from output parameters
	for _, param := range stmt.Returns {
		if param.WithChannel() {
			channels = append(channels, ast.NewIdent(param.ChannelName(varPool)))
		}
	}

	if len(channels) == 0 {
		return nil
	}

	return stmt.channelsClose(channels)
}
