// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeService() *Service {
	apikey := kessoku.Provide(NewAPIKey).Fn()()
	databaseURL := kessoku.Provide(NewDatabaseURL).Fn()()
	service := kessoku.Provide(NewService).Fn()(apikey, databaseURL)
	return service
}
