// Code generated by kessoku. DO NOT EDIT.

package main

import "github.com/mazrean/kessoku"

func InitializeApp() (*App, error) {
	var err error
	config, err := kessoku.Provide(NewConfig).Fn()()
	if err != nil {
		var zero *App
		return zero, err
	}
	var err0 error
	database, err0 := kessoku.Provide(NewDatabase).Fn()(config)
	if err0 != nil {
		var zero *App
		return zero, err0
	}
	var err1 error
	cache, err1 := kessoku.Provide(NewCache).Fn()(config)
	if err1 != nil {
		var zero *App
		return zero, err1
	}
	var err2 error
	service, err2 := kessoku.Provide(NewService).Fn()(database, cache)
	if err2 != nil {
		var zero *App
		return zero, err2
	}
	app := kessoku.Provide(NewApp).Fn()(service)
	return app, nil
}
